name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Markdown Linting Action
      uses: avto-dev/markdown-lint@v1.1.0
